footgear/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from footgear import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('filter/', views.FilterProductView.as_view(), name='filter'),
    path('groups/', views.GroupsView.as_view(), name='groups'),
    path('anyway/', views.anyway, name='anyway'),
    path("<slug:slug>/", views.ProductDetailView.as_view(), name="product_detail"),
    path('category/<slug:category_slug>/', views.CategoryView.as_view(), name='category'),
    path('cart', views.cart_detail, name='cart_detail'),
    path('cart/add/<int:product_id>', views.add_cart, name='add_cart'),
    path('cart/remove/<int:product_id>', views.cart_remove, name='cart_remove'),
    path('cart/remove_product/<int:product_id>', views.cart_remove_product, name='cart_remove_product'),

]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=250, unique=True, verbose_name='Категорія')
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)
    showcase = models.BooleanField(default=True, verbose_name='Вітрина')

    def get_absolute_url(self):
        return reverse('category', kwargs={'category_slug': self.slug})

    class Meta:
        ordering = ('id',)
        verbose_name = 'Категорію'
        verbose_name_plural = 'Категорії'

    def __str__(self):
        return self.name


class Size(models.Model):
    size = models.CharField(max_length=250, verbose_name='Розмір')

    class Meta:
        ordering = ('id',)
        verbose_name = 'Розмір'
        verbose_name_plural = 'Розміри'

    def __str__(self):
        return self.size


class Type(models.Model):
    type = models.CharField(max_length=250, verbose_name='Тип')

    class Meta:
        ordering = ('id',)
        verbose_name = 'Типів'
        verbose_name_plural = 'Типи'

    def __str__(self):
        return self.type


class Style(models.Model):
    style = models.CharField(max_length=250, verbose_name='Стиль')

    class Meta:
        ordering = ('id',)
        verbose_name = 'Стилів'
        verbose_name_plural = 'Стилі'

    def __str__(self):
        return self.style


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True, verbose_name='Товар')
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True, verbose_name='Опис')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категорія')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Ціна')
    image = models.ImageField(upload_to='product', blank=True, verbose_name='Зображення')
    vendor_code = models.CharField(max_length=250, unique=True, verbose_name='Артикул')
    stock = models.IntegerField(verbose_name='Кількість, шт.')
    available = models.BooleanField(default=True, verbose_name='Наявність')
    showcase = models.BooleanField(default=True, verbose_name='Вітрина')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Створено')
    updated = models.DateTimeField(auto_now=True, verbose_name='Оновлено')
    size = models.ManyToManyField(Size, verbose_name='Розмір')
    type = models.ManyToManyField(Type, verbose_name='Тип')
    style = models.ManyToManyField(Style, verbose_name='Стиль')

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'slug': self.slug})

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товари'
        verbose_name_plural = 'Товари'

    def __str__(self):
        return self.name


class Slider(models.Model):
    name = models.CharField(max_length=250, unique=True, verbose_name='Слайдер')
    image = models.ImageField(upload_to='slider', blank=True, verbose_name='Зображення')
    published = models.BooleanField(default=True, verbose_name='Опубліковано')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Слайдер'
        verbose_name_plural = 'Слайдер'

    def __str__(self):
        return self.name


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ['date_added']
        db_table = 'Cart'

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product

shop/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView

from .models import *


class SizeTypeStyle:
    @staticmethod
    def get_sizes():
        return Size.objects.all()

    @staticmethod
    def get_types():
        return Type.objects.all()

    @staticmethod
    def get_styles():
        return Style.objects.all()


class Home(SizeTypeStyle, ListView):
    model = Product
    template_name = 'shop/home.html'
    context_object_name = 'products'

    def get_queryset(self):
        return Product.objects.filter(available=True, showcase=True)[:8]

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Взуттєво, що не кажи'
        return context


# class ProductView(SizeTypeStyle, ListView):
#     paginate_by = 8
#     model = Product
#     queryset = Product.objects.filter(available=True)


class ProductDetailView(SizeTypeStyle, DetailView):
    model = Product
    slug_field = "slug"


class CategoryView(SizeTypeStyle, ListView):
    model = Product

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['category_slug'], available=True)


class GroupsView(SizeTypeStyle, ListView):
    paginate_by = 8
    model = Product
    template_name = 'shop/groups.html'

    def get_queryset(self):
        return Product.objects.filter(available=True)


class FilterProductView(SizeTypeStyle, ListView):
    def get_queryset(self):
        queryset = Product.objects.filter(
            Q(size__in=self.request.GET.getlist("size")) |
            Q(type__in=self.request.GET.getlist("type")) |
            Q(style__in=self.request.GET.getlist("style"))
        )
        return queryset


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
        cart_item.save()

    return redirect('cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'shop/cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart_detail')


def cart_remove_product(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart_detail')


def anyway(request):
    return render(request, 'shop/anyway.html')

shop/templates/shop/anyway.html
{% extends 'base.html' %}

{% block content %}
<div class="main-anyway">
    <h1> Сторінка в розробці</h1>
</div>
{% endblock %}

shop/templates/shop/cart.html
{% extends 'base.html' %}

{% block content %}
<div class="main">
    <div class="card__wrapper">
        {% if not cart_items %}
        <div class="cart-title">
            <br>
            <h1>
                Ваш кошик порожній
            </h1>
            <br>
            <p>
                Перейти <a href="{% url 'home' %}">сюди</a> для замовлення
            </p>
        </div>

        {% else %}
        <div class="cart-title">
            <br>
            <div>
                <h1><strong>Кошик</strong></h1>
            </div>
        </div>
        <div class="cart-detail">
            <div>
                <table>
                    <thead>
                    <tr>
                        <th class="cart-row">
                            Ваше замовлення
                        </th>
                    </tr>
                    </thead>
                    {% for cart_item in cart_items %}
                    <tr>
                        <td class="cart-row">
                            <a href="{{cart_item.product.get_url}}">
                                <img src="{{cart_item.product.image.url}}" width="100" height="100">
                            </a>
                        </td>
                        <td class="cart-row">
                            {{cart_item.product.name}}
                            <br>
                            Артикул: {{cart_item.product.vendor_code}}
                            <br>
                            Ціна {{cart_item.product.price}}
                            <br><br>
                            Всього: {{cart_item.quantity}} * {{cart_item.product.price}}
                            <br>
                        </td>
                        <td class="cart-row">
                            {{cart_item.product.sub_total}}
                        </td>
                        {% if cart_item.quantity < cart_item.product.stock %}
                        <td class="cart-row">
                            <a href="{% url 'add_cart' cart_item.product.id %}"><span
                                    class="material-icons arrow">add</span></a>
                            <a href="{% url 'cart_remove' cart_item.product.id %}"><span
                                    class="material-icons arrow">remove</span></a>
                            <a href="{% url 'cart_remove_product' cart_item.product.id %}">
                                <span class="material-icons arrow">delete</span>
                            </a>
                        </td>
                        {% else %}
                        <td class="cart-row">
                            <a href="{% url 'cart_remove' cart_item.product.id %}"><span
                                    class="material-icons arrow">remove</span></a>
                            <a href="{% url 'cart_remove_product' cart_item.product.id %}"><span
                                    class="material-icons arrow">delete</span></a>
                        </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </table>
            </div>
            <div>
                <table>
                    <thead>
                    <tr>
                        <th class="cart-row">
                            Перевірка
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="cart-row">
                            Будь ласка перевірте ваше замовлення
                        </td>
                    </tr>
                    <tr>
                        <td class="cart-row">
                            Ваше замовлення на сумму: <strong>{{total}} грн</strong>
                        </td>
                    </tr>
                    </tbody>
                </table>
                <div class="cart-row">
                    <a href="{% url 'home' %}">
                        <button type="button" class="pay-button__buy">
                            На головну
                        </button>
                    </a>
                    <a href="{% url 'home' %}">
                        <button type="button" class="pay-button__buy">
                            Замовити
                        </button>
                    </a>
                </div>

            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

shop/templates/shop/groups.html
{% load shop_tags %}

{% block content %}

{% get_all_categories %}

{% include 'shop/product_list.html' %}

{% endblock %}

shop/templates/shop/home.html
{% extends 'base.html' %}

{% block content %}
{% include 'include/slider.html' %}
<div class="product-wrapper">
    {% include 'include/sidebar.html' %}
    <div class="product-list">
        <div class="product-list__title">Вітрина</div>
        <div class="product-list__list">
            {% for product in products %}
            <div class="product-list__card product-card">
                {% if product.image %}
                <div class="product-card__img">
                    <a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" alt=""></a>
                </div>
                {% endif %}
                <div class="product-card__content">
                    <div class="product-card__title">{{ product.name }}</div>
                    <div class="product-card__artic">
                        <div class="product-card__stock">В наявності</div>
                        <div class="product-card__code">{{ product.vendor_code }}</div>
                    </div>
                    <div class="product-card__price">{{ product.price }}</div>
                    <button type="button" class="product-card__button"
                            onclick="window.location.href = '{% url 'add_cart' product.id %}';">В кошик
                    </button>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% include 'include/description.html' %}
{% endblock %}

shop/templates/shop/product_detail.html
{% extends 'base.html' %}
{% load shop_tags %}

{% block content %}

<div class="main">
    <div class="card__wrapper">
        <div class="card__container">
            <div class="card__img">
                <img src="{{ product.image.url }}" alt="">
            </div>
            <div class="card__order order-items">
                <div class="order-items__title">
                    <h1>{{ product.name }}</h1>
                </div>
                <div class="order-items__price">{{ product.price }}</div>
                <div class="order-items__specific">Склад: 80% бавовна, 15% поліамід, 5% еластан</div>
                <div class="order-items__variety variety-list">
                    <div class="variety-list__title">Розмір</div>
                    <div class="variety-list__list">
                        {% for size in product.size.all %}
                        <div class="variety-list__item">{{ size }}</div>
                        {% endfor %}
                    </div>
                </div>
                <div class="pay-button">
                    <div class="pay-button__wrap">
                        <div class="pay-button__button"><span class="material-icons pay__ico">remove</span></div>
                        <div class="pay-button__count">1</div>
                        <div class="pay-button__button"><span class="material-icons pay__ico">add</span></div>
                    </div>
                    <button type="button" class="pay-button__buy"
                            onclick="window.location.href = '{% url 'add_cart' product.id %}';">Додати у кошик
                    </button>
                </div>
            </div>
        </div>
        <div class="card-description">
            <p>{{ product.description }}</p>
        </div>
        <div class="card-other">
            <div class="product-list__title">Схожi товари</div>
            {% get_random_products as products %}
            <div class="product-list__list">
                {% for product in products %}
                <div class="product-list__card product-card">
                    {% if product.image %}
                    <div class="product-card__img">
                        <a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" alt=""></a>
                    </div>
                    {% endif %}
                    <div class="product-card__content">
                        <div class="product-card__title">{{ product.name }}</div>
                        <div class="product-card__artic">
                            <div class="product-card__stock">В наявності</div>
                            <div class="product-card__code">{{ product.vendor_code }}</div>
                        </div>
                        <div class="product-card__price">{{ product.price }}</div>
                        <button type="button" class="product-card__button"
                                onclick="window.location.href = '{% url 'add_cart' product.id %}';">В кошик
                        </button>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

shop/templates/shop/product_list.html
{% extends 'base.html' %}

{% block content %}
<div class="product-wrapper">
    {% include 'include/sidebar.html' %}
    <div class="product-list">
        <div class="product-list__title">Каталог</div>
        <div class="product-list__list">
            {% for product in product_list %}
            <div class="product-list__card product-card">
                {% if product.image %}
                <div class="product-card__img">
                    <a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" alt=""></a>
                </div>
                {% endif %}
                <div class="product-card__content">
                    <div class="product-card__title">{{ product.name }}</div>
                    <div class="product-card__artic">
                        <div class="product-card__stock">В наявності</div>
                        <div class="product-card__code">{{ product.vendor_code }}</div>
                    </div>
                    <div class="product-card__price">{{ product.price }}</div>
                    <button type="button" class="product-card__button"
                            onclick="window.location.href = '{% url 'add_cart' product.id %}';">В кошик
                    </button>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% if page_obj.has_other_pages %}
<nav class="list-pages">
    <ul class="ul-pages">
        {% if page_obj.has_previous %}
        <li class="page-num">
            <a href="?page={{ page_obj.previous_page_number }}" class="a-page-num">&lt;</a>
        </li>
        {% endif %}

        {% for p in paginator.page_range %}
        {% if page_obj.number == p %}
        <li class="page-num page-num-selected">{{ p }}</li>
        {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
        <li class="page-num">
            <a href="?page={{ p }}" class="a-page-num">{{ p }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-num">
            <a href="?page={{ page_obj.next_page_number }}" class="a-page-num">&gt;</a>
        </li>
        {% endif %}

    </ul>
</nav>
{% endif %}
{% endblock %}